sensor_kit_base_link:
  camera0/camera_link: # Front Corner Camrea
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  camera1/camera_link: # Front Stereo Camera
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  camera2/camera_link: # Rear Corner Camera
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  Lidar_top_base_link: # Ouster OS1-128
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  Lidar_front_base_link: # Livox HAP 
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  # Radar_front_base_link: # Front 4D Radar
  #   x: 0.0
  #   y: 0.0
  #   z: 0.0
  #   roll: 0.0
  #   pitch: 0.0
  #   yaw: 0.0
  GNSS_INS/gnss_ins_link: # GNSS Antenna
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  # tamagawa/imu_link: # IMU ..?
  #   x: 0.0
  #   y: 0.0
  #   z: 0.0
  #   roll: 0.0
  #   pitch: 0.0
  #   yaw: 0.0
