sensor_kit_base_link:
  front_camera_joint/front_camera_link: 
    x: 0.535
    y: 0.0
    z: 0.168
    roll: 0.0
    pitch: 1.5708
    yaw: 0.0
  top_lidar_joint/top_lidar_link: # Ouster OS1-128 (TOP)
    x: -0.15144
    y: 0.0
    z: 2.08
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  front_lidar_joint/front_lidar_link: # Livox HAP (FRONT)
    x: 0.38206
    y: 0.0
    z: 1.71
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  # Radar_front_base_link: # Front 4D Radar
  #   x: 0.0
  #   y: 0.0
  #   z: 0.0
  #   roll: 0.0
  #   pitch: 0.0
  #   yaw: 0.0
  gps_antenna_main_joint/gps_antenna_main_link: # GNSS Antenna
    x: -0.01144
    y: 0.6525
    z: 1.7
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  gps_antenna_aux_joint/gps_antenna_aux_link: # GNSS Antenna/base link
    x: -0.01144
    y: 0.6525
    z: 1.7
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  imu_joint/imu_link: # IMU ..?
    x: -0.004387
    y: 0.0
    z: 0.18294
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
